---
name: Action Major Tag
on:
  push:
    tags: ['v[0-9]+.[0-9]+.[0-9]+']
jobs:
  new-major-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Run Action Major Tagger
        uses: discoverygarden/action-major-tag@v1
        with:
          prefix: v
