---
name: Build image from version tag

permissions:
  id-token: write
  contents: read
on:
  push:
    tags: [ v** ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    if: (github.event_name == "push" && github.event.push.created) || github.event_name == "pull_request"
    uses: ./.github/workflows/build-image.yml
    secrets: inherit
    with:
      image-name: ${{ vars.DOCKER_IMAGE_NAME }}
